package ${packageName};

import javax.persistence.*;
import java.io.Serializable;
import java.sql.*;

@Entity
@Table(name = "${tableName}")
public class ${tableNameFirstUpper}Bean implements Serializable {

private static final long serialVersionUID = 1L;
<#-- Generate Variables -->
<#list columns as col>
    ${col.primaryKey ? string ("@Id", "")}
    ${col.autoGeneratedId ? string ("@GeneratedValue(strategy = GenerationType.IDENTITY)", "")}
    @Column(name = "${col.columnName}")
    private ${col.columnDataTypeInJava} ${col.columnNameFirstLower};
</#list>

<#-- Generate getter/setter -->
<#list columns as col>
    public ${col.columnDataTypeInJava} get${col.columnNameFirstUpper}() {
        return ${col.columnNameFirstLower};
    }

    public void set${col.columnNameFirstUpper}(${col.columnDataTypeInJava} ${col.columnNameFirstLower}) {
        this.${col.columnNameFirstLower} = ${col.columnNameFirstLower};
    }

</#list>
}
