package com.ifish.tool.bean;

import java.io.Serializable;

public class ColumnBean implements Serializable {

    public String tableName;

    public String tableNameFirstUpper;

    public String columnName;

    public String columnNameFirstUpper;

    public String columnNameFirstLower;

    public String columnDataType;

    public String columnDataTypeInJava;

    public boolean primaryKey;

    public boolean autoGeneratedId;

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getTableNameFirstUpper() {
        return tableNameFirstUpper;
    }

    public void setTableNameFirstUpper(String tableNameFirstUpper) {
        this.tableNameFirstUpper = tableNameFirstUpper;
    }

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public String getColumnNameFirstUpper() {
        return columnNameFirstUpper;
    }

    public void setColumnNameFirstUpper(String columnNameFirstUpper) {
        this.columnNameFirstUpper = columnNameFirstUpper;
    }

    public String getColumnNameFirstLower() {
        return columnNameFirstLower;
    }

    public void setColumnNameFirstLower(String columnNameFirstLower) {
        this.columnNameFirstLower = columnNameFirstLower;
    }

    public String getColumnDataType() {
        return columnDataType;
    }

    public void setColumnDataType(String columnDataType) {
        this.columnDataType = columnDataType;
    }

    public String getColumnDataTypeInJava() {
        return columnDataTypeInJava;
    }

    public void setColumnDataTypeInJava(String columnDataTypeInJava) {
        this.columnDataTypeInJava = columnDataTypeInJava;
    }

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public void setPrimaryKey(boolean primaryKey) {
        this.primaryKey = primaryKey;
    }

    public boolean isAutoGeneratedId() {
        return autoGeneratedId;
    }

    public void setAutoGeneratedId(boolean autoGeneratedId) {
        this.autoGeneratedId = autoGeneratedId;
    }
}
